/* THIS FILE IS AUTO-GENERATED BY Makefile */
#include "mp_version.h"
const char * const mp_git_sha = "54d42b1";
const int mp_version_major = MP_VERSION_MAJOR;
const int mp_version_minor = MP_VERSION_MINOR;
const int mp_version_patch = MP_VERSION_PATCH;
const char * const mp_version_string = MP_VERSION_STRING(MP_VERSION_MAJOR,MP_VERSION_MINOR,MP_VERSION_PATCH) "-54d42b1";
const char * const mp_version_component = "mod_python/" MP_VERSION_STRING(MP_VERSION_MAJOR,MP_VERSION_MINOR,MP_VERSION_PATCH) "-54d42b1";